### ISSUE TITLE
[BUG] Ensure token-wrapper fee recipient has existential deposit

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/protocol-substrate#326]
**Issue summary**
The token wrapper pallet sends the fee for every wrap call to the fee recipient address, if the fee recipient address does not already have ED, the transfer will fail with `Existential Deposit` error for small amounts. 

```rust
T::Currency::transfer(
			from_currency_id,
			&from,
			&Self::get_fee_recipient(&asset_details.name),
			Self::get_wrapping_fee(amount, into_pool_share_id)?,
		)?;
```

We need to populate the fee recipient address with ED at genesis or consider an alternate approach for fee here.

https://github.com/webb-tools/protocol-substrate/blob/f0c637dc00625f65a7df28acd2d5f463c5f833c3/pallets/token-wrapper/src/lib.rs#L436

**Comment by shekohex** [comment]
Adding some funds to the fee recipient address is not the best solution here, since we technically could change the fee recipient at any point using proposal-like [runtime transaction](https://github.com/webb-tools/protocol-substrate/blob/f0c637dc00625f65a7df28acd2d5f463c5f833c3/pallets/token-wrapper-handler/src/lib.rs#L154-L154) or [directly](https://github.com/webb-tools/protocol-substrate/blob/f0c637dc00625f65a7df28acd2d5f463c5f833c3/pallets/token-wrapper/src/lib.rs#L231) using sudo, for example.

A better way is to expose [get_amount_to_wrap](https://github.com/webb-tools/protocol-substrate/blob/f0c637dc00625f65a7df28acd2d5f463c5f833c3/pallets/token-wrapper/src/lib.rs#L340-L347) using a storage/RPC or a runtime call for example so that the user have to first consider the amount they will need to input + fees. This method will take the amount that I want to wrap and returns the total amount (including the fees) that I can pass to the token wrapper or the vanchor. On the other side, this method also should consider that the `fees >= existential deposit` and returns a more readable error for the user.

**Comment by drewstone** [comment]
Is this still in progress @1xstj ? It is in the completed section but still open. Please use completed for issues that are only completed in fact.
